version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_booking
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "5433:5432"
      # 5433 — это порт на твоей машине (host), то есть ты будешь подключаться к базе через localhost:5433, 
      # 5432 — это внутренний порт в контейнере, на котором PostgreSQL всегда работает по умолчанию
    volumes:
      # это путь к postgres_data_booking
      - postgres_data_booking:/var/lib/postgresql/data

# это надо чтоб докер не удалял данные при перезапуске контейнера и сам создал папку
volumes:
  postgres_data_booking:
