services:
  # Dedicated service for installing dependencies once
  postgres_db:
    image: postgres:latest
    container_name: postgres_booking
    restart: always
    environment:
      POSTGRES_USER: yeqorka
      POSTGRES_PASSWORD: test228
      POSTGRES_DB: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres_data_booking:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_booking
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data_booking:/data

  nginx:
    container_name: nginx_booking
    build:
      context: .
      dockerfile: nginx/DockerFile
    ports:
      - '80:80'

volumes:
  postgres_data_booking:
  redis_data_booking: